<footer id="footer">
  <div class="row clearfix">
    <div id="footer-utility-links">
      <ul class="menu gt-footer-utility-links">
        <li class="first"><b>If you encounter issues with the website or need help, please contact <a href="mailto:its@ce.gatech.edu?Subject=Data%20Submission%20Website%20Issues" target="_top">its@ce.gatech.edu</a>. Thank You for your support!</b></li>
       <!--  <li class="last"><a href="mailto:its@ce.gatech.edu?Subject=Data%20Submission%20Website%20Issues" title="" class="active">Contact Us</a></li> -->
      </ul>
      <ul class="menu custom-links-included">
        <li><a href="http://www.gatech.edu/emergency/">Emergency Information</a></li>
        <li><a href="http://www.gatech.edu/legal/">Legal &amp; Privacy Information</a></li>
		<li><a href="http://www.gatech.edu/accessibility/">Accessibility</a></li>
        <li><a href="http://www.gatech.edu/accountability/">Accountability</a></li>
		<li><a href="https://www.gatech.edu/accreditation/">Accreditation</a></li>
        <li><a href="http://www.careers.gatech.edu">Employment</a></li>
        <!-- <li class="site-login last"><a href="/user">Login</a></li> -->
       </ul> 
    </div>
    <div id="footer-logo">
      <a href="http://www.gatech.edu/"><img alt="Georgia Tech" src="/images/gt-logo-footer-retina.png" ></a>
      <p>&copy; 2016 Georgia Institute of Technology</p>
    </div>
  </div>
</footer><!-- /footer -->
