<header id="masthead">
  <section id="identity" class="clearfix">
    <div id="identity-wrapper">
      <h1 id="gt-logo">
        <a href="https://ce.gatech.edu" title="Georgia Tech" ><img alt="Georgia Tech" src="/images/logos/logo-gt-hi-rez.png" /></a>
      </h1>
      <!-- class="one-line" // Class for single tag line -->
      <h2 class="two-line" id="site-title" rel="home"><a href="https://ce.gatech.edu">Creating the Next<br>Changing the World</a></h2>
    </div>
  </section>
  <section id="primary-menus">
    <div id="primary-menus-wrapper" class="clearfix">
      <a id="primary-menus-toggle" class="hide-for-desktop"><span>Menu</span></a>
      <div id="primary-menus-off-canvas" class="off-canvas">
        <a id="primary-menus-close" class="hide-for-desktop"><span>Close</span></a>
        <div id="utility">
          <div class="row clearfix">
            <nav id="utility-links">
              <ul class="menu">
                <li class="mothership ulink"><a href="http://www.gatech.edu" title="Georgia Tech Home" >Georgia Tech Home</a></li>
                <li class="campus-map ulink"><a href="http://www.map.gatech.edu" title="Map" >Map</a></li>
                <li class="directories ulink"><a href="http://www.gatech.edu/directory" title="Directory" >Directory</a></li>
                <li class="offices ulink"><a href="http://www.gatech.edu/departments" title="Offices" >Offices</a></li>
              </ul>
            </nav>
            <div id="social-media-links-wrapper">
              <ul id="social-media-links">
                <li class="first"><a href="https://www.facebook.com/georgiatech" title="Facebook" class="facebook">Facebook</a></li>
                <li><a href="http://www.flickr.com/photos/georgiatech" title="Flickr" class="flickr">Flickr</a></li>
                <li><a href="https://plus.google.com/+georgiatech/posts" title="Google Plus" class="googleplus">Google Plus</a></li>
                <li><a href="http://www.linkedin.com/company/3558" title="LinkedIn" class="linkedin">LinkedIn</a></li>
                <li><a href="http://pinterest.com/georgiatech/" title="Pinterest" class="pinterest">Pinterest</a></li>
                <li><a href="http://gatech.edu/rss" title="RSS" class="rss">RSS</a></li>
                <li><a href="https://twitter.com/georgiatech" title="Twitter" class="twitter">Twitter</a></li>
                <li class="last"><a href="http://www.youtube.com/georgiatech" title="YouTube" class="youtube">YouTube</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
<!--       <div id="site-search">
        <a id="site-search-container-switch">Search</a>
        <div id="site-search-container">
          <div id="search-gt">
            <form action="http://search.gatech.edu/search" method="get">
            <input  value="" name="q" id="q" class="form-text" type="text" />
            <input name="site" value="default_collection" type="hidden" />
            <input name="client" value="default_frontend" type="hidden" />
            <input name="output" value="xml_no_dtd" type="hidden" />
            <input name="proxystylesheet" value="default_frontend" type="hidden" />
            <input name="proxyreload" value="1" type="hidden" /></form>
          </div>
        </div>
      </div>
 --> 
     <center><h2>Impact of Smartphone Applications on Trip Routing</h2></center>  
<!--                              <a href="#" data-toggle="popover" title="Popover Header" data-content="You need to satisfy all of the above criteria to proceed with the data donation for this research study.">Note</a>
 -->                
 
     </div>
    <!--     <div id="breadcrumb" class="hide-for-mobile">
      <div class="row clearfix">
        <ul>
          <li class="breadcrumb-item first"><a href="http://www.gatech.edu" title="GT Home" >GT Home</a></li>
        </ul>
      </div>
    </div>
 -->  
  </section>
</header>