<!--
  /**
   * Superfooter Options
   *
   * What is marked up below contains the full list of default superfooter links from www.gatech.edu.
   * See the "default mini" links (commented out) below if you wish to only display the "GT Resources" links,
   * and "Visitor Resources" links. You will also need to change the class of the section#superfooter element
   * to use 'superfooter-gt-default-mini' instead of 'superfooter-gt-default-full'.
   * If you don't want a collapsible superfooter just remove the "collapsible" class from the 
   * section#superfooter element, and comment out or remove the div.superfooter-trigger-wrapper element.
   *
   */
-->
<div class="superfooter-trigger-wrapper clearfix"><a class="js__superfooter-trigger collapsed" href="#superfooter" id="superfooter-trigger">Resources</a></div>
<section id="superfooter" class="superfooter-gt-default-full collapsible">
  <div class="row clearfix">
  
    <div class="superfooter-resource-links" id="gt-default-resource-links">
      <h4 class="title">Georgia Tech Resources</h4>
      <ul class="menu" id="gt-default-resources">
          <li><a href="http://www.gatech.edu/offices-and-departments">Offices &amp; Departments</a></li>
      		<li><a href="http://www.news.gatech.edu">News Center</a></li>
      		<li><a href="http://www.gatech.edu/calendar">Campus Calendar</a></li>
      		<li><a href="http://www.specialevents.gatech.edu">Special Events</a></li>
      		<li><a href="http://www.greenbuzz.gatech.edu">GreenBuzz</a></li>
     		  <li><a href="http://www.comm.gatech.edu">Institute Communications</a></li>
          <li><span class="nolink">Visitor Resources</span></li>
					<li><a href="http://www.admission.gatech.edu/visit">Campus Visits</a></li>
					<li><a href="http://www.gatechhotel.com">Georgia Tech Hotel &amp; Conference Center</a></li>
					<li><a href="http://www.glc.gatech.edu">Georgia Tech Global Learning Center</a></li>
					<li><a href="http://www.pts.gatech.edu/visitors/Pages/default.aspx">Visitor Parking Information</a></li>
					<li><a href="http://www.admission.gatech.edu/visit/directions-and-parking">Directions to Campus</a></li>
					<li><a href="http://www.lawn.gatech.edu/help/GTvisitor.html">GTvisitor Wireless Network Information</a></li>
					<li><a href="http://www.gatech.bncollege.com">Barnes &amp; Noble at Georgia Tech</a></li>
					<li><a href="http://www.ferstcenter.gatech.edu">Robert Ferst Center for the Arts</a></li>
					<li><a href="http://www.ipst.gatech.edu/amp">Robert C. Williams Paper Museum</a></li>
      </ul>
    </div>
    
    <!--  Superfooter default 'mini' links : GT Resources -- >
    <!--
    <div id="gt-default-resource-links" class="superfooter-resource-links">
      <h4 class="title">Georgia Tech Resources</h4>
      <ul id="gt-default-resources" class="menu">
        <li><a href="http://www.gatech.edu/offices-and-departments">Offices &amp; Departments</a></li>
        <li><a href="http://www.news.gatech.edu">News Center</a></li>
        <li><a href="http://www.gatech.edu/calendar">Campus Calendar</a></li>
        <li><a href="http://www.specialevents.gatech.edu">Special Events</a></li>
        <li><a href="http://www.greenbuzz.gatech.edu">GreenBuzz</a></li>
        <li><a href="http://www.comm.gatech.edu">Institute Communications</a></li>
      </ul>
    </div>
    -->
    
    <!--  Superfooter default 'mini' links : Visitor Resources -- >
    <!--
    <div id="gt-default-visitor-links" class="superfooter-resource-links">
      <h4 class="title">Visitor Resources</h4>
      <ul id="gt-visitor-resources" class="menu"><li class="gt-default-mini-left"><a href="http://www.admission.gatech.edu/visit">Campus Visits</a></li>
        <li class="gt-default-mini-right"><a href="http://www.admission.gatech.edu/visit/directions-and-parking">Directions to Campus</a></li>
        <li class="gt-default-mini-left"><a href="http://www.pts.gatech.edu/visitors/Pages/default.aspx">Visitor Parking Information</a></li>
        <li class="gt-default-mini-right"><a href="http://www.lawn.gatech.edu/help/GTvisitor.html">GTvisitor Wireless Network Information</a></li>
        <li class="gt-default-mini-left"><a href="https://pe.gatech.edu/global-learning-center/">Georgia Tech Global Learning Center</a></li>
        <li class="gt-default-mini-right"><a href="http://www.gatechhotel.com">Georgia Tech Hotel &amp; Conference Center</a></li>
        <li class="gt-default-mini-left"><a href="http://www.gatech.bncollege.com">Barnes &amp; Noble at Georgia Tech</a></li>
        <li class="gt-default-mini-right"><a href="http://www.ferstcenter.gatech.edu">Ferst Center for the Arts</a></li>
        <li class="gt-default-mini-left"><a href="http://www.ipst.gatech.edu/amp">Robert C. Williams Paper Museum</a></li>
      </ul>
    </div>
    -->
    
    <div class="superfooter-resource-links" id="gt-footer-links-1">
      <h4 class="title">Colleges &amp; Campuses</h4>
      <ul class="menu"><li class="first"><span title="" class="nolink">Colleges</span></li>
					<li><a href="http://www.coa.gatech.edu">College of Architecture</a></li>
					<li><a href="http://www.cc.gatech.edu">College of Computing</a></li>
					<li><a href="http://www.coe.gatech.edu">College of Engineering</a></li>
					<li><a href="http://www.cos.gatech.edu">College of Sciences</a></li>
					<li><a href="http://www.iac.gatech.edu">Ivan Allen College of Liberal Arts</a></li>
					<li><a href="http://www.scheller.gatech.edu">Scheller College of Business</a></li>
          <li><span class="nolink">Global Presence</span></li>
					<li><a href="http://pe.gatech.edu/savannah-campus">Savannah</a></li>
					<li><a href="http://tip.gatech.edu/">Costa Rica</a></li>
					<li><a href="http://lorraine.gatech.edu/">France</a></li>
					<li><a href="http://pku.bme.gatech.edu/">Peking University Joint Degree Program</a></li>
					<li><a href="http://www.tliap.nus.edu.sg/">Singapore</a></li>
			    <li><span class="nolink">Research</span></li>
					<li><a href="http://www.research.gatech.edu">Research at Georgia Tech</a></li>
      		<li><a href="http://www.research.gatech.edu/evpr">Executive Vice President for Research</a></li>
      </ul>
    </div>
    
    <div class="superfooter-resource-links"  id="gt-footer-links-2">
      <h4 class="title">Student &amp; Parent Resources</h4>
      <ul class="menu">
        <li><span class="nolink">Student Resources</span></li>
					<li><a href="http://www.gatech.edu/admissions">Apply</a></li>
					<li><a href="http://www.buzzport.gatech.edu">BuzzPort</a></li>
					<li><a href="http://www.buzzcard.gatech.edu">Buzzcard</a></li>
					<li><a href="http://career.gatech.edu/">Career Services</a></li>
					<li><a href="http://profpractice.gatech.edu/">Co-ops &amp; Internships</a></li>
					<li><a href="http://www.commencement.gatech.edu/">Commencement</a></li>
					<li><a href="http://www.library.gatech.edu">Library</a></li>
					<li><a href="http://studentaffairs.gatech.edu/">Student Affairs</a></li>
					<li><a href="http://startup.gatech.edu/">Student Entrepreneurship</a></li>
					<li><a href="http://oie.gatech.edu/study-abroad">Study Abroad</a></li>
					<li><a href="http://www.tsquare.gatech.edu">T-Square</a></li>
          <li><span class="nolink">Parent Resources</span></li>
					<li><a href="http://www.parents.gatech.edu">Parents Program</a></li>
					<li><a href="http://www.deanofstudents.gatech.edu/">Dean of Students</a></li>
					<li><a href="http://www.finaid.gatech.edu/">Scholarships &amp; Financial Aid</a></li>
      </ul>
    </div>
        
    <div class="superfooter-resource-links" id="gt-footer-links-3">
      <h4 class="title">Employee, Alumni, &amp; Other Resources</h4>
      <ul class="menu">
         <li><span class="nolink">Employees</span></li>
					<li><a href="http://www.af.gatech.edu/">Administration and Finance</a></li>
					<li><a href="http://advising.gatech.edu/">Advising &amp; Teaching</a></li>
					<li><a href="http://facultygovernance.gatech.edu/">Faculty Governance</a></li>
					<li><a href="http://careers.gatech.edu/">Faculty Hiring</a></li>
					<li><a href="http://www.ohr.gatech.edu">Human Resources</a></li>
					<li><a href="http://www.provost.gatech.edu">Office of the Provost</a></li>
					<li><a href="http://www.techworks.gatech.edu">TechWorks</a></li>
          <li><span class="nolink">Alumni</span></li>
					<li><a href="http://www.gtalumni.org">Alumni Association</a></li>
					<li><a href="http://gtalumni.org/pages/career">Alumni Career Services</a></li>
					<li><a href="http://gtalumni.org/pages/rollcall">Giving Back to Tech</a></li>
          <li><span class="nolink">Outreach</span></li>
					<li><a href="http://www.atdc.org/">Startup Companies</a></li>
					<li><a href="http://www.innovate.gatech.edu/">Economic Development</a></li>
					<li><a href="http://www.industry.gatech.edu/">Industry Engagement</a></li>
					<li><a href="http://www.gov.gatech.edu/">Government &amp; Community Partners</a></li>
					<li><a href="http://gtri.gatech.edu/">Georgia Tech Research Institute</a></li>
					<li><a href="http://pe.gatech.edu/">Professional Education</a></li>
      </ul>
    </div>
    
    <div id="street-address-info">
      <a href="http://www.map.gatech.edu"><img alt="Map of Georgia Tech" src="/images/gt-map-image-default.jpg" /></a>
      <div class="street-address">
        <p>Georgia Institue of Technology<br />
        North Avenue, Atlanta, GA 30332<br />
        Phone: 404-894-2000</p>
      </div>
    </div>
    
  </div>
</section><!-- /superfooter -->
